version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow_frontend
    ports:
      - "3000:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend_taskflow_network
    restart: unless-stopped

networks:
  backend_taskflow_network:
    external: true
